studio/studio/urls.py
from django.contrib import admin
from django.urls import path, include
from web.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name='index'),
    path('manager/edit_order/<int:order_id>/', edit_order, name='edit_order'),
    path('manager/requests/', requests, name='requests'),
    path('manager/executors/', executors, name='executors'),
    path('manager/executors/<int:pk>/delete/', delete_executor, name='delete_executor'),
    path('manager/executors/<int:pk>/edit/', edit_executor, name='edit_executor'),
    path('manager/feedback/', feedback_list, name='feedback'),
    path('manager/feedback/<int:pk>/delete/', delete_feedback, name='delete_feedback'),
    path('manager/', manager, name='manager'),

    path('client/order/', order, name='order'),
    path('client/myorders/', myorders, name='myorders'),
    path('delete_request/<int:request_id>/', delete_request, name='delete_request'),
    path('client/answers/', answers, name='answers'),
    path('client/', client, name='client'),
    path('register/', registration_view, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studio/web/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#Common Models
class DesignCategory(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Категории дизайна'

class Feedback(models.Model):
    fullname = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname} - {self.subject}"
    
    class Meta:
        verbose_name_plural = 'Обратная связь'
    

# Client

class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=100)
    email = models.EmailField()
    category = models.ForeignKey(DesignCategory, on_delete=models.CASCADE)
    project_description = models.TextField()
    attachment = models.FileField(upload_to='attachments/')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname} - {self.category.name} Request"
    
    class Meta:
        verbose_name_plural = 'Заявки'

# Manager

class Executor(models.Model):
    fullname = models.CharField(max_length=100)
    photo = models.FileField(upload_to='photo/')
    bio = models.TextField()
    skills = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.fullname} - {self.skills}"
    
    class Meta:
        verbose_name_plural = 'Исполнитель'

class ClientOrder(models.Model):
    client = models.ForeignKey(Request, on_delete=models.CASCADE)
    assigned_executor = models.ForeignKey(Executor, on_delete=models.CASCADE, null=True, blank=True)
    status_choices = [
        ('assigned', 'Назначен'),
        ('in_progress', 'В работе'),
        ('completed', 'Завершен'),
        ('canceled', 'Отменен'),
    ]
    status = models.CharField(max_length=20, choices=status_choices, default='assigned')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} - {self.client.fullname} - {self.status}"
    
    class Meta:
        verbose_name_plural = 'Обработка заявок'

studio/templates/answers.html
{% extends 'style.html' %}
{% load static %}


{% block nav_block %}


<li class="nav-item">
  <a class="nav-link" href="{% url 'order' %}">Оформить заявку</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'myorders' %}">Мои заявки</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'answers' %}">Обработка заявок</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
</li>


{% endblock %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center mb-3">Обработанные заявки</h3>

    {% for order in processed_orders %}
      <div class="card mb-3">
        <div class="card-header bg-success-subtle">
          <strong>ФИО:</strong> {{ order.client.fullname }}<br>
          <strong>Почта:</strong> {{ order.client.email }}
        </div>
        <div class="card-body">
          <h5 class="card-title"><strong>Категория проекта:</strong> {{ order.client.category.name }}</h5>
          <p class="card-text"><strong>Описание проекта:</strong> {{ order.client.project_description }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Исполнитель:</strong> {% if order.assigned_executor %}{{ order.assigned_executor.fullname }}{% else %}Не назначен{% endif %}</li>
          <li class="list-group-item"><strong>Статус заявки:</strong> {{ order.get_status_display }}</li>
        </ul>
      </div>
    {% endfor %}

    <div class="pagination">
      <span class="step-links">
          {% if processed_orders.has_previous %}
              <a class="btn-styled" href="?page=1">&laquo; первая</a>
              <a class="btn-styled" href="?page={{ processed_orders.previous_page_number }}">предыдущая</a>
          {% endif %}

          <span class="current">
              Страница {{ processed_orders.number }} из {{ processed_orders.paginator.num_pages }}.
          </span>

          {% if processed_orders.has_next %}
              <a class="btn-styled" href="?page={{ processed_orders.next_page_number }}">следующая</a>
              <a class="btn-styled" href="?page={{ processed_orders.paginator.num_pages }}">последняя &raquo;</a>
          {% endif %}
      </span>
    </div>

  </div>

{% endblock %}

studio/templates/client.html
{% extends 'style.html' %}
{% load static %}


{% block nav_block %}


<li class="nav-item">
  <a class="nav-link" href="#">Оформить заявку</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Мои заявки</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Обработка заявок</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
</li>


{% endblock %}

{% block content %}

<br>
<br>

<div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <img src="{% static 'images/logout.png' %}" alt="Выход из аккаунта" class="img-fluid mb-4">
        <h3>Добро пожаловать, {{user.username}}</h3>
        <p>Ваша роль: Клиент</p>
        <p>Ведутся работы</p>
        <br>
        <a class="btn-styled" href="{% url 'index' %}">Вернуться на главную</a>
      </div>
    </div>
</div>




{% endblock %}

studio/templates/edit_executor.html
{% extends 'style.html' %}
{% load static %}


{% block content %}

<div class="container">
<br>
<br>
<div class="row justify-content-center">
<br>
<form method="post" action="{% url 'edit_executor' executor.id %}" class="col-md-5" enctype="multipart/form-data" class="col-md-6">
    {% csrf_token %}
    <br>
    <h2>Редактирование исполнителя: {{ executor.fullname }}</h2>
    <br>
    <div class="mb-3">
        <label for="id_fullname" class="form-label">ФИО</label>
        <input type="text" name="fullname" class="form-control" id="id_fullname" value="{{ executor.fullname }}" required>
    </div>

    <div class="mb-3">
        <label for="id_photo" class="form-label">Фото</label>
        <input type="file" name="photo" class="form-control" id="id_photo">
    </div>

    <div class="mb-3">
        <label for="id_bio" class="form-label">Биография</label>
        <textarea name="bio" class="form-control" id="id_bio" required>{{ executor.bio }}</textarea>
    </div>

    <div class="mb-3">
        <label for="id_skills" class="form-label">Навыки</label>
        <input type="text" name="skills" class="form-control" id="id_skills" value="{{ executor.skills }}" required>
    </div>

    <button type="submit" class="btn-styled">Сохранить</button>
    <br>
    <br>
</form>
</div>
</div>

{% endblock %}

studio/templates/edit_order.html
{% extends 'style.html' %}

{% block nav_block %}

<li class="nav-item">
  <a class="nav-link" href="{% url 'requests' %}">Панель заявок</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'executors' %}">Панель исполнителей</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'feedback' %}">Панель обратной связи</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
</li>

{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
    <h3 class="text-center mb-3">Назначение исполнителя и установка статуса заказа</h3>
    <h5 class="text-center mb-3">Заказ {{ order.id }}</h5>

    <form method="post" action="" class="col-md-6">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn-styled">Сохранить</button>
    </form>
</div>

  </div>
{% endblock %}

studio/templates/executors.html
{% extends 'style.html' %}
{% load static %}



{% block nav_block %}

<li class="nav-item">
  <a class="nav-link" href="{% url 'requests' %}">Панель заявок</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'executors' %}">Панель исполнителей</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'feedback' %}">Панель обратной связи</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
</li>

{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <form method="post" action="{% url 'executors' %}" class="col-md-5" enctype="multipart/form-data">
            {% csrf_token %}
            <br>
            <br>
            <h3 class="text-center">Добавить исполнителя</h3>
            <br>
            <div class="mb-3">
                <label for="id_fullname" class="form-label">ФИО</label>
                <input type="text" name="fullname" class="form-control" id="id_fullname" placeholder="Введите ФИО" required>
            </div>
    
            <div class="mb-3">
                <label for="id_photo" class="form-label">Фото</label>
                <input type="file" name="photo" class="form-control" id="id_photo" required>
            </div>
    
            <div class="mb-3">
                <label for="id_bio" class="form-label">Биография</label>
                <textarea name="bio" class="form-control" id="id_bio" placeholder="Введите биографию" required></textarea>
            </div>
    
            <div class="mb-3">
                <label for="id_skills" class="form-label">Навыки</label>
                <input type="text" name="skills" class="form-control" id="id_skills" placeholder="Введите навыки" required>
            </div>
    
            <button type="submit" class="btn-styled">Добавить</button>
            <br>
            <br>
        </form>
        <div class="col-md-7">
            <br>
            <br>
            <form method="get" action="{% url 'executors' %}" class="col-md-8">
                <div class="mb-3">
                    <label for="search" class="form-label">Поиск</label>
                    <input type="text" name="search" class="form-control" id="search" placeholder="Введите имя либо фамилию" value="{{ request.GET.search }}">
                </div>
                <button type="submit" class="btn-styled">Искать</button>
            </form>
            <br>
            {% for executor in execs %}
            <div class="col-md-8 mb-4">
              <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{ executor.photo.url }}" class="img-fluid rounded-start" alt="{{ executor.fullname }}">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{ executor.fullname }}</h5>
                      <p class="card-text">{{ executor.skills }}</p>
                      <div class="card-footer">
                        <a href="{% url 'delete_executor' pk=executor.pk %}" class="btn btn-danger">Удалить</a>
                        <a href="{% url 'edit_executor' pk=executor.pk %}" class="btn btn-primary">Изменить</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

studio/templates/feedback.html
{% extends 'style.html' %}
{% load static %}



{% block nav_block %}

<li class="nav-item">
  <a class="nav-link" href="{% url 'requests' %}">Панель заявок</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'executors' %}">Панель исполнителей</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'feedback' %}">Панель обратной связи</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
</li>

{% endblock %}

{% block content %}
<div class="container">
<br>
<br>
<h2>Обратная связь</h2>
  <br>
  {% for feedback in feedbacks %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title bg-success-subtle">{{ feedback.fullname }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ feedback.subject }}</h6>
        <p class="card-text">{{ feedback.message }}</p>
        <p class="card-text">{{ feedback.email }}</p>
        <p class="card-text">{{ feedback.timestamp }}</p>
        <a href="{% url 'delete_feedback' feedback.id %}" class="btn btn-danger">Удалить</a>
        <a href="https://mail.google.com/mail/u/0/#inbox?compose=new" class="btn btn-primary" target="_blank">Ответить</a>
      </div>
    </div>
  {% endfor %}
  
  <br>
  <br> 

  <div class="pagination">

    <span class="step-links">
        {% if feedbacks.has_previous %}
            <a class = "btn-styled" href="?page=1">&laquo; первая</a>
            <a class = "btn-styled" href="?page={{ feedbacks.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ feedbacks.number }} из {{ feedbacks.paginator.num_pages }}.
        </span>

        {% if feedbacks.has_next %}
            <a class = "btn-styled" href="?page={{ feedbacks.next_page_number }}">следующая</a>
            <a class = "btn-styled" href="?page={{ feedbacks.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
        <br>
        <br>
    </span>
  </div>
  </div>


{% endblock %}

studio/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Design pro</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <body>
        <!-- Навигационная панель -->
        <nav class="navbar navbar-expand-lg navbar-dark" style = "background-color: blueviolet; color: aliceblue;">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'images/logo.png' %}" alt="Design Pro" height="30"> Design Pro
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#services">Услуги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#executors">Специалисты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#price-list">Прайс</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#feedback">Связь</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">     </a>
                        </li>

                        {% if user.is_authenticated %}
                    <!-- Если пользователь авторизован -->
                    {% if user.is_active and user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'manager' %}">{{ user.username }}</a>
                    </li>
                    {% elif user.is_active %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'client' %}">{{ user.username }}</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                    </li>
                    {% else %}
                    <!-- Если пользователь не авторизован -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                    </li>
                    {% endif %}
                
                    </ul>
                </div>
            </div>
        </nav>
    
        <!-- Офферная конструкция -->
        <section class="container my-5">
            <div class="row">
                <div class="col-md-6">
                    <h1 id="about-us" >Дизайн-студия Design Pro</h1>
                    <p>Добро пожаловать в наш мир дизайна, где каждый проект — это уникальное произведение искусства, рожденное из ваших мечтаний и нашего творческого вдохновения.</p>
                    <p>Наши дизайнеры — мастера создания впечатляющих и неповторимых визуальных решений</p>
                    <br>
                    <h4>Цели нашей студии</h4>
                    <br>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <i class="bi bi-check2 text-success"></i> Воплотить уникальные идеи клиентов в эстетически привлекательные дизайн-концепции.
                        </li>
                        <li class="list-group-item">
                            <i class="bi bi-check2 text-success"></i> Поддерживать инновационные тенденции в графическом дизайне и внедрять их в наши проекты.
                        </li>
                        <li class="list-group-item">
                            <i class="bi bi-check2 text-success"></i> Обеспечить высокий стандарт качества в каждом аспекте нашей творческой работы.
                        </li>
                        <li class="list-group-item">
                            <i class="bi bi-check2 text-success"></i> Создавать долгосрочные партнерства с клиентами, основанные на взаимном доверии и успешных результатов.
                        </li>
                    </ul>
                    <br>
                    <a class="btn-styled" href="{% url 'login' %}">Заказать дизайн</a>
                    <br>
                </div>

                <div class="col-md-6">
                    <img src="{% static 'images/offer.png' %}" alt="Офферная конструкция" class="img-fluid">
                </div>
            </div>
        </section>
    
        <section class="container my-5">
            <h2 id="services">Услуги</h2>
            <br>
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/s-1.png' %}" class="card-img-top" alt="Услуга 1">
                        <div class="card-body">
                            <h5 class="card-title">Логотипы и Брендинг</h5>
                            <p class="card-text">Мы создаем уникальные логотипы и бренды, которые подчеркивают уникальность вашего бизнеса.</p>
                        </div>
                    </div>
                </div>
        
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/s-2.jpg' %}" class="card-img-top" alt="Услуга 2">
                        <div class="card-body">
                            <h5 class="card-title">Веб-дизайн</h5>
                            <p class="card-text">Мы разрабатываем креативные и удобные веб-сайты, подчеркивая ваше онлайн-присутствие.</p>
                        </div>
                    </div>
                </div>
        
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/s-3.jpg' %}" class="card-img-top" alt="Услуга 3">
                        <div class="card-body">
                            <h5 class="card-title">Дизайн cоциальных Сетей</h5>
                            <p class="card-text">Привлекайте внимание к вашему бренду через креативные графические материалы в социальных сетях.</p>
                        </div>
                    </div>
                </div>
        </section>
    

        <section class="container my-5">
            <h2 id="executors">Наши специалисты</h2>
            <br>
            <div class="row">
                {% for executor in executors %}
                    <div class="col-md-4 mb-4">
                        <div class="card text-center">
                            <img src="{{ executor.photo.url }}" alt="{{ executor.fullname }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ executor.fullname }}</h5>
                                <p class="card-text">{{ executor.skills }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </section>
    

        <section class="container my-5">
            <h2 id="price-list">Прайс-лист</h2>
            <br>
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/l-1.jpg' %}" class="card-img-top" alt="Логотип">
                        <div class="card-body">
                            <h5 class="card-title">Логотип</h5>
                            <p class="card-text">Уникальный и запоминающийся логотип для вашего бренда.</p>
                            <p class="card-text">Цена: <strong>$500</strong></p>
                        </div>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/l-2.jpg' %}" class="card-img-top" alt="Брендинг">
                        <div class="card-body">
                            <h5 class="card-title">Брендинг</h5>
                            <p class="card-text">Разработка уникального стиля для вашего бренда.</p>
                            <p class="card-text">Цена: <strong>$800</strong></p>
                        </div>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/l-3.jpg' %}" class="card-img-top" alt="Оформление Instagram">
                        <div class="card-body">
                            <h5 class="card-title">Оформление Instagram</h5>
                            <p class="card-text">Создание стильного дизайна для вашего Instagram аккаунта.</p>
                            <p class="card-text">Цена: <strong>$300</strong></p>
                        </div>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/l-4.jpg' %}" class="card-img-top" alt="Web-дизайн на Tilda">
                        <div class="card-body">
                            <h5 class="card-title">Web-дизайн на Tilda</h5>
                            <p class="card-text">Создание красивого и функционального веб-дизайна на платформе Tilda.</p>
                            <p class="card-text">Цена: <strong>$600</strong></p>
                        </div>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/l-5.jpg' %}" class="card-img-top" alt="Графический дизайн">
                        <div class="card-body">
                            <h5 class="card-title">Графический дизайн</h5>
                            <p class="card-text">Разработка различных графических элементов для вашего бизнеса.</p>
                            <p class="card-text">Цена: <strong>$400</strong></p>
                        </div>
                    </div>
                </div>
    
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{% static 'images/l-6.jpg' %}" class="card-img-top" alt="Разработка web-приложения">
                        <div class="card-body">
                            <h5 class="card-title">Разработка web-приложения</h5>
                            <p class="card-text">Создание современного и удобного веб-приложения для вашего бизнеса.</p>
                            <p class="card-text">Цена: <strong>$1200</strong></p>
                        </div>
                    </div>
                </div>
            </div>

        </section>

        <section class="container my-5">
            <h2 id="feedback">Обратная связь</h2>
            <br>
            <form class = "feedback" method="post" action="#">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                    {{ form.as_p }}
                    <br>
                    <button type="submit" class="btn-styled">Отправить</button>
                    </div>

                    <div class="col-md-6">
                    <img src="{% static 'images/feedback.png' %}" alt="Изображение" class="img-fluid">
                    </div>
                </div>
            </form>
        </section>

        <footer class="bg-light text-center py-3">
            <p>&copy; 2023 Design Pro. Все права защищены.</p>
        </footer>
    
    
</body>
</html>

studio/templates/manager.html
{% extends 'style.html' %}
{% load static %}

{% block content %}

<br>
<br>

<div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <img src="{% static 'images/logout.png' %}" alt="Выход из аккаунта" class="img-fluid mb-4">
        <h3>Добро пожаловать, {{user.username}}</h3>
        <p>Ваша роль: Сотрудник</p>
        <p>Ведутся работы</p>
        <br>
        <a class="btn-styled" href="{% url 'index' %}">Вернуться на главную</a>
      </div>
    </div>
</div>




{% endblock %}

studio/templates/myorders.html
{% extends 'style.html' %}
{% load static %}


{% block nav_block %}


<li class="nav-item">
  <a class="nav-link" href="{% url 'order' %}">Оформить заявку</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'myorders' %}">Мои заявки</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'answers' %}">Обработка заявок</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
</li>


{% endblock %}

{% block content %}
<div class="container mt-5">
    <h3 class="text-center mb-3">Список заявок</h3>

    <form method="get" action="{% url 'myorders' %}">
      <div class="mb-3">
        <label for="categoryFilter">Фильтр по категории:</label>
        <select name="category" class="form-control" id="categoryFilter">
          <option value="" {% if not category_filter %}selected{% endif %}>Все</option>
          {% for category in categories %}
            <option value="{{ category.name }}" {% if category_filter == category.name %}selected{% endif %}>{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn-styled">Применить</button>
    </form>
    <br>

        {% for request in requests %}
        <br>
            <div class="card">
              <h5 class="card-header bg-success-subtle">{{ request.fullname }}</h5>
              <div class="card-body">
                <h5 class="card-title">{{ request.category.name }}</h5>
                <p class="card-text">{{ request.project_description }}</p>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Email:</strong> {{ request.email }}</li>
                <li class="list-group-item"><strong>Дата создания:</strong> {{ request.timestamp }}</li>
              </ul>
              <div class="card-body">
                <a href="{% url 'delete_request' request.id %}" class="btn btn-danger">Удалить</a>
              </div>
          </div>
        {% endfor %}


    <div class="mt-3">
      {% if requests.has_other_pages %}
        <ul class="pagination">
          {% if requests.has_previous %}
            <li class="page-item"><a class="btn-styled" href="?page={{ requests.previous_page_number }}">Предыдущая</a></li>
          {% endif %}
          {% for i in requests.paginator.page_range %}
            <li class="page-item {% if requests.number == i %}active{% endif %}"><a class="btn-styled" href="?page={{ i }}">{{ i }}</a></li>
          {% endfor %}
          {% if requests.has_next %}
            <li class="page-item"><a class="btn-styled" href="?page={{ requests.next_page_number }}">Следующая</a></li>
          {% endif %}
        </ul>
      {% endif %}
    </div>

  </div>

{% endblock %}